package Vista;

import java.awt.Image;
import java.net.URL;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author Jefferson Granados
 * En esta clase se implementa la interfaz de Gestión de
 * Productos. Permite ingresar datos del producto, seleccionar categoría y
 * mostrar/filtrar imágenes desde la carpeta /img según la categoría elegida.
 */
public class GestionProductos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionProductos.class.getName());

    private final Mensajes mensajes = new Mensajes();

    private DefaultListModel<ItemImagen> modeloImagenes;

    private static final java.util.Map<String, String> IMG_CAT = new java.util.HashMap<>();

    static {

        IMG_CAT.put("prod_ArrozCamarones.png", "Comidas");
        IMG_CAT.put("prod_ArrozConAtun.png", "Comidas");
        IMG_CAT.put("prod_Casado.png", "Comidas");
        IMG_CAT.put("prod_DesayunoAmericano.png", "Comidas");
        IMG_CAT.put("prod_EmpanadaCarne.png", "Comidas");
        IMG_CAT.put("prod_HuevoFrito.png", "Comidas");
        IMG_CAT.put("prod_PescadoFrito.png", "Comidas");
        IMG_CAT.put("prod_SopaPollo.png", "Comidas");
        IMG_CAT.put("prod_SopaTomate.png", "Comidas");
        IMG_CAT.put("prod_TacoCarnitas.png", "Comidas");
        IMG_CAT.put("prod_TacoPollo.png", "Comidas");
        IMG_CAT.put("prod_TamalCerdo.png", "Comidas");
        IMG_CAT.put("prod_TortillasPalmeadas.png", "Comidas");

        IMG_CAT.put("prod_Brownie.png", "Postres");
        IMG_CAT.put("prod_CheeseCakeFresa.png", "Postres");
        IMG_CAT.put("prod_CheeseCakeLimon.png", "Postres");
        IMG_CAT.put("prod_DonaCaramelo.png", "Postres");
        IMG_CAT.put("prod_QuequeChocolate.png", "Postres");
        IMG_CAT.put("prod_QuequeVainilla.png", "Postres");

        IMG_CAT.put("prod_TazaCafe.png", "Cafe");
        IMG_CAT.put("prod_TazaCafeExpresso.png", "Cafe");
        IMG_CAT.put("prod_TazaCafeFrio.png", "Cafe");
        IMG_CAT.put("prod_TazaCapuccino.png", "Cafe");

        IMG_CAT.put("prod_CocaColaGod.png", "Bebidas");
        IMG_CAT.put("prod_CocaColaNoGod.png", "Bebidas");
        IMG_CAT.put("prod_Fanta.png", "Bebidas");
        IMG_CAT.put("prod_GaseosaDrpepper.png", "Bebidas");
        IMG_CAT.put("prod_Sprite.png", "Bebidas");
        IMG_CAT.put("prod_Naranjada.png", "Bebidas");
        IMG_CAT.put("prod_NaturalFresa.png", "Bebidas");
        IMG_CAT.put("prod_NaturalOrchata.png", "Bebidas");

        IMG_CAT.put("prod_BatidoChocolate.png", "Lacteos");
        IMG_CAT.put("prod_YogurtFresa.png", "Lacteos");
        IMG_CAT.put("prod_BatidoMora.png", "Lacteos");
        IMG_CAT.put("prod_BatidoOreo.png", "Lacteos");

    }

    /**
     * Creates new form GestionProducto Constructor: inicializa componentes y
     * configura el formulario. Se ocultan campos internos y se prepara la lista
     * de imágenes.
     */
    public GestionProductos() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        setSize(789, 580);

        txtImagen.setEditable(false);
        txtImagen.setVisible(false);
        lblImgPro.setVisible(false);

        jScrollPane1.setVisible(true);

        configurarListaImagenes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtImagen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListImagenes = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIDProduct = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lblImgPro = new javax.swing.JLabel();
        lblPreviewImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel2.setBackground(new java.awt.Color(215, 227, 225));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        btnCancelar.setBackground(new java.awt.Color(239, 68, 68));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnGuardar.setBackground(new java.awt.Color(37, 99, 235));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar Producto");
        btnGuardar.setFocusPainted(false);
        btnGuardar.setPreferredSize(new java.awt.Dimension(100, 31));
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        txtImagen.addActionListener(this::txtImagenActionPerformed);

        jListImagenes.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jListImagenes);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestion Productos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(465, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID");

        txtIDProduct.addActionListener(this::txtIDProductActionPerformed);

        labelNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(0, 0, 0));
        labelNombre.setText("Nombre");

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Precio$");

        txtPrecio.addActionListener(this::txtPrecioActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Descripción de Producto");

        txtDescripcion.addActionListener(this::txtDescripcionActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Cantidad en Stock");

        txtCantidad.addActionListener(this::txtCantidadActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(17, 24, 39));
        jLabel3.setText("Categoría");

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lacteos", "Postres", "Cafe", "Bebidas", "Comidas" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(labelNombre)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIDProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblImgPro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblImgPro.setForeground(new java.awt.Color(0, 0, 0));
        lblImgPro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgPro.setText("Imagen de producto");

        lblPreviewImg.setBackground(new java.awt.Color(255, 255, 255));
        lblPreviewImg.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImgPro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreviewImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblImgPro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPreviewImg, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtIDProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDProductActionPerformed

    private void txtImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImagenActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnCancelarActionPerformed

    public javax.swing.JTextField getTxtImagen() {
        return txtImagen;
    }

    public static Logger getLogger() {
        return logger;
    }

    public JComboBox<String> getComboCategoria() {
        return comboCategoria;
    }

    public JButton getjButton11() {
        return btnGuardar;
    }

    public JButton getjButton8() {
        return btnCancelar;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JLabel getjLabel6() {
        return lblImgPro;
    }

    public javax.swing.JLabel getLblPreviewImg() {
        return lblPreviewImg;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public JSeparator getjSeparator2() {
        return jSeparator2;
    }

    public JLabel getLabelNombre() {
        return labelNombre;
    }

    public JTextField getTxtCantidad() {
        return txtCantidad;
    }

    public JTextField getTxtDescripcion() {
        return txtDescripcion;
    }

    public JTextField getTxtIDProduct() {
        return txtIDProduct;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public JTextField getTxtPrecio() {
        return txtPrecio;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public javax.swing.JList<String> getJListImagenes() {
        return jListImagenes;
    }

    /**
     * Escala una imagen manteniendo proporción y evitando deformación. Se setea
     * el tamaño de los iconos aparte de editarse desde el navegador de archivos
     * para evitar deformaciones
     *
     * @return ImageIcon escalado proporcionalmente
     */
    private ImageIcon escalarProporcional(ImageIcon icono, int maxW, int maxH) {
        int w = icono.getIconWidth();
        int h = icono.getIconHeight();

        if (w <= 0 || h <= 0) {
            return icono;
        }

        double scale = Math.min((double) maxW / w, (double) maxH / h);
        int newW = (int) Math.round(w * scale);
        int newH = (int) Math.round(h * scale);

        Image img = icono.getImage().getScaledInstance(newW, newH, Image.SCALE_SMOOTH);
        return new ImageIcon(img);
    }

    /**
     * Limpia el formulario y deja los campos listos para un nuevo registro.
     */
    public void limpiarFormulario() {
        txtIDProduct.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtCantidad.setText("");
        txtDescripcion.setText("");
        txtImagen.setText("");
        comboCategoria.setSelectedIndex(0);
    }

    /**
     * Clase interna: representa un item de la lista de imágenes. Guarda el
     * nombre del archivo y su icono.
     */
    private static class ItemImagen {

        private String nombre;
        private ImageIcon icono;

        public ItemImagen(String nombre, ImageIcon icono) {
            this.nombre = nombre;
            this.icono = icono;
        }

        public String getNombre() {
            return nombre;
        }

        public ImageIcon getIcono() {
            return icono;
        }

        @Override
        public String toString() {
            return nombre;
        }

    }

    /**
     * Filtra las imágenes del JList según la categoría seleccionada. Reinicia
     * selección y preview.
     */
    public void filtrarImagenesPorCategoria(String categoria) {
        if (modeloImagenes == null) {
            return;
        }

        cargarImagenesPNGEnModelo(modeloImagenes, categoria);

        jListImagenes.clearSelection();
        txtImagen.setText("");
        lblPreviewImg.setIcon(null);
        lblImgPro.setVisible(false);

        revalidate();
        repaint();
    }

    /**
     * Configura el modelo del JList, su renderer y el listener de selección.
     * También aplica el filtro inicial usando la categoría actual.
     */
    private void configurarListaImagenes() {

        modeloImagenes = new DefaultListModel<>();
        jListImagenes.setModel((javax.swing.ListModel) modeloImagenes);

        jListImagenes.setCellRenderer(new javax.swing.DefaultListCellRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(
                    javax.swing.JList<?> list, Object value, int index,
                    boolean isSelected, boolean cellHasFocus) {

                JLabel label = (JLabel) super.getListCellRendererComponent(
                        list, "", index, isSelected, cellHasFocus);

                label.setHorizontalAlignment(JLabel.CENTER);
                label.setVerticalAlignment(JLabel.CENTER);

                if (value instanceof ItemImagen item) {
                    label.setIcon(escalarProporcional(item.getIcono(), 90, 90));

                    label.setText(""); // solo imagen
                } else {
                    label.setIcon(null);
                }

                return label;
            }
        });

        filtrarImagenesPorCategoria(comboCategoria.getSelectedItem().toString());

        jListImagenes.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                Object sel = jListImagenes.getSelectedValue();
                if (sel instanceof ItemImagen item) {
                    txtImagen.setText(item.getNombre());
                    Image img = item.getIcono().getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
                    getLblPreviewImg().setIcon(new ImageIcon(img));
                    lblImgPro.setVisible(true);

                    revalidate();
                    repaint();
                }
            }
        });
    }

    /**
     * Carga las imágenes desde /img, filtra por categoría y las agrega al
     * modelo. Si falta la carpeta, muestra mensaje usando la clase Mensajes.
     */
    /**
     * Carga las imágenes desde /img, filtra por categoría y las agrega al
     * modelo. Si falta la carpeta o ocurre un error, se notifica usando la
     * clase Mensajes.
     */
    private void cargarImagenesPNGEnModelo(DefaultListModel<ItemImagen> modelo, String categoriaFiltro) {
        modelo.clear();

        try {
            URL url = getClass().getResource("/img");
            if (url == null) {
                mensajes.message("No existe la carpeta /img en resources");
                return;
            }

            java.io.File carpeta = new java.io.File(url.toURI());
            java.io.File[] archivos = carpeta.listFiles();
            if (archivos == null) {
                return;
            }

            for (java.io.File archivo : archivos) {
                String nombre = archivo.getName();
                String lower = nombre.toLowerCase();

                // Solo toma archivos PNG que empiecen con "prod_"
                if (!lower.endsWith(".png") || !lower.startsWith("prod_")) {
                    continue;
                }

                // Obtiene la categoría de la imagen según el mapa
                String catImg = IMG_CAT.get(nombre);

                // Si la imagen tiene categoría asignada, se filtra por la categoría seleccionada
                if (catImg != null) {
                    if (categoriaFiltro != null
                            && !categoriaFiltro.isBlank()
                            && !catImg.equalsIgnoreCase(categoriaFiltro)) {
                        continue;
                    }
                }

                // Carga la imagen y la agrega al modelo del JList
                URL imgUrl = getClass().getResource("/img/" + nombre);
                if (imgUrl != null) {
                    ImageIcon icono = new ImageIcon(imgUrl);
                    modelo.addElement(new ItemImagen(nombre, icono));
                }
            }

        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error cargando imágenes", ex);
            mensajes.message("Ocurrió un error cargando las imágenes.");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jListImagenes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel lblImgPro;
    private javax.swing.JLabel lblPreviewImg;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIDProduct;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
