/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Product;
import java.awt.*;
import java.net.URL;
import javax.swing.*;

/**
 *
 * @author Personal
 */
public class OrderItemCard extends javax.swing.JPanel {

    /**
     * Creates new form OrderItemCard
     */
    public OrderItemCard() {
        initComponents();
    }

    private JLabel lblCant;

    public OrderItemCard(Product p, int cantidad, Runnable onMinus, Runnable onPlus, Runnable onDelete) {

        setBackground(new Color(245, 245, 245));
        setBorder(BorderFactory.createEmptyBorder(8, 8, 8, 8));
        setLayout(new BorderLayout(8, 0));

        // Importante: BoxLayout del panelResumen usa el ancho del contenedor
        setMaximumSize(new Dimension(Integer.MAX_VALUE, 64));
        setPreferredSize(new Dimension(10, 64));
        setMinimumSize(new Dimension(10, 64));

        // ===== Imagen izquierda =====
        JLabel img = new JLabel();
        img.setPreferredSize(new Dimension(44, 44));
        img.setHorizontalAlignment(SwingConstants.CENTER);
        img.setIcon(cargarIcono("/img/" + p.getImage(), 38, 38));
        add(img, BorderLayout.WEST);

        // ===== Centro (nombre + precio) =====
        JPanel center = new JPanel();
        center.setOpaque(false);
        center.setLayout(new BoxLayout(center, BoxLayout.Y_AXIS));

        JLabel nombre = new JLabel(p.getNameProduct());
        nombre.setFont(new Font("Segoe UI", Font.BOLD, 12));

        JLabel precio = new JLabel("₡" + (int) p.getPrice() + " c/u");
        precio.setForeground(new Color(120, 120, 120));
        precio.setFont(new Font("Segoe UI", Font.PLAIN, 11));

        center.add(nombre);
        center.add(Box.createVerticalStrut(2));
        center.add(precio);

        add(center, BorderLayout.CENTER);

        // ===== Derecha (botones) =====
        JPanel right = new JPanel(new FlowLayout(FlowLayout.RIGHT, 4, 0));
        right.setOpaque(false);

        JButton btnMinus = btnCuadrado("-", new Color(0, 140, 255));
        JButton btnPlus  = btnCuadrado("+", new Color(0, 140, 255));
        JButton btnDel   = btnCuadrado("X", new Color(255, 80, 80));

        lblCant = new JLabel(String.valueOf(cantidad));
        lblCant.setPreferredSize(new Dimension(16, 22));
        lblCant.setHorizontalAlignment(SwingConstants.CENTER);
        lblCant.setFont(new Font("Segoe UI", Font.BOLD, 11));

        btnMinus.addActionListener(e -> onMinus.run());
        btnPlus.addActionListener(e -> onPlus.run());
        btnDel.addActionListener(e -> onDelete.run());

        right.add(btnMinus);
        right.add(lblCant);
        right.add(btnPlus);
        right.add(btnDel);

        add(right, BorderLayout.EAST);
    }

    private JButton btnCuadrado(String text, Color bg) {
        JButton b = new JButton(text);

        b.setPreferredSize(new Dimension(20, 20)); // más pequeño
        b.setMargin(new Insets(0, 0, 0, 0));
        b.setFont(new Font("Segoe UI", Font.BOLD, 11));

        b.setBackground(bg);
        b.setForeground(Color.WHITE);

        b.setFocusPainted(false);
        b.setBorderPainted(false);
        b.setContentAreaFilled(true);
        b.setOpaque(true);

        return b;
    }

    private ImageIcon cargarIcono(String path, int w, int h) {
        URL url = getClass().getResource(path);
        if (url == null) return null;

        Image img = new ImageIcon(url).getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
        return new ImageIcon(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
