/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Product;
import Modelo.Product;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;

/**
 *
 * @author Personal
 */
public class panelProduct extends javax.swing.JPanel {

    /**
     * Creates new form panelProduct
     */
    public panelProduct() {
        initComponents();
    }

    public panelProduct(Product p) {
        setPreferredSize(new Dimension(160, 150));
        setBackground(Color.WHITE);
        setBorder(javax.swing.BorderFactory.createLineBorder(new Color(210, 210, 210)));
        setLayout(new BorderLayout());

        // ===== TOP (imagen) =====
        JPanel top = new JPanel(new BorderLayout());
        top.setBackground(new Color(210, 210, 210));
        top.setPreferredSize(new Dimension(75, 75));

        JLabel lblImg = new JLabel("", JLabel.CENTER);
        lblImg.setIcon(cargarIcono("/img/" + p.getImage(), 70, 70));
        top.add(lblImg, BorderLayout.CENTER);

        // ===== BOTTOM (texto) =====
        JPanel bottom = new JPanel();
        bottom.setBackground(Color.WHITE);
        bottom.setLayout(new BoxLayout(bottom, BoxLayout.Y_AXIS));
        bottom.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 8, 6, 8));
        bottom.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

        JLabel lblName = new JLabel(p.getNameProduct());
        lblName.setFont(new Font("Segoe UI", Font.BOLD, 13));
        lblName.setForeground(Color.BLACK);
        lblName.setHorizontalAlignment(JLabel.LEFT);
        lblName.setMaximumSize(new Dimension(Integer.MAX_VALUE, 18));
        lblName.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

        JLabel lblCat = new JLabel(p.getCategory());
        lblCat.setFont(new Font("Segoe UI", Font.PLAIN, 11));
        lblCat.setForeground(new Color(90, 90, 90));
        lblCat.setHorizontalAlignment(JLabel.LEFT);
        lblCat.setMaximumSize(new Dimension(Integer.MAX_VALUE, 16));
        lblCat.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

        JSeparator sep = new JSeparator();
        sep.setForeground(new Color(220, 220, 220));
        sep.setMaximumSize(new Dimension(Integer.MAX_VALUE, 1));
        sep.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

        JPanel fila = new JPanel(new BorderLayout());
        fila.setOpaque(false);
        fila.setMaximumSize(new Dimension(Integer.MAX_VALUE, 20));
        fila.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

        JLabel lblPrecio = new JLabel("₡" + (int) p.getPrice());
        lblPrecio.setForeground(new Color(0, 140, 0));
        lblPrecio.setFont(new Font("Segoe UI", Font.BOLD, 12));

        JLabel lblStock = new JLabel("Stock: " + p.getCant());
        lblStock.setForeground(new Color(140, 140, 140));
        lblStock.setFont(new Font("Segoe UI", Font.PLAIN, 11));

        fila.add(lblPrecio, BorderLayout.WEST);
        fila.add(lblStock, BorderLayout.EAST);

        bottom.add(lblName);
        bottom.add(Box.createVerticalStrut(1));
        bottom.add(lblCat);
        bottom.add(Box.createVerticalStrut(5));
        bottom.add(sep);
        bottom.add(Box.createVerticalStrut(5));
        bottom.add(fila);

        add(top, BorderLayout.NORTH);
        add(bottom, BorderLayout.CENTER);
    }

    private ImageIcon cargarIcono(String path, int w, int h) {
        URL url = getClass().getResource(path);
        if (url == null) {
            return null;
        }

        Image img = new ImageIcon(url).getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
        return new ImageIcon(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
