/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import Control.ControllerGestionMesas;
import Control.ControllerClients;
import Control.ControllerInventario;
import Control.ControllerOrder;
import Control.controladorProductosPanel;
import Modelo.ClientsDAO;
import Modelo.productosDAO;
import Vista.ClientsPanel;
import Vista.GestionCliente;
import Vista.GestionFacturacion;
import Vista.GestionInventario;
import Vista.GestionMesas;
import Vista.Products;
import Vista.orders;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author dh057
 */
public class Principal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);

        JPanel vacio = new JPanel();

        orders ord = new orders();
        Products p = new Products();
        GestionInventario inv = new GestionInventario();
        GestionMesas mesas = new GestionMesas();
        GestionFacturacion fact = new GestionFacturacion();
        ClientsPanel clientsPanel = new ClientsPanel();
        GestionCliente gestionCliente = new GestionCliente();
    

        panelContenido.add(vacio, "vacio");
        panelContenido.add(ord, "order");
        panelContenido.add(p, "products");
        panelContenido.add(inv, "inventario");
        panelContenido.add(mesas, "mesas");
        panelContenido.add(fact, "facturacion");
        panelContenido.add(clientsPanel, "clients");
     

        productosDAO prodDao = productosDAO.getInstancia();
        ClientsDAO clientsDao = new ClientsDAO();
        
        ControllerGestionMesas mesasCtrl = new ControllerGestionMesas(mesas);

        ControllerInventario invCtrl = new ControllerInventario(inv);

        new controladorProductosPanel(p, invCtrl);

        // orders (buscar cliente, etc.)
        new ControllerOrder(ord);

        // clients
        new ControllerClients(clientsPanel, clientsDao, gestionCliente);
        
     
    }

//        panelContenido.add(new Reportes(), "reportes");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnProducts = new javax.swing.JButton();
        btnClients = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnMesas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnFacturacion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        panelContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 700));

        jPanel1.setBackground(new java.awt.Color(215, 227, 225));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cafeteria UCR");

        btnProducts.setBackground(new java.awt.Color(33, 150, 243));
        btnProducts.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnProducts.setText("Productos");
        btnProducts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducts.setBorderPainted(false);
        btnProducts.setContentAreaFilled(false);
        btnProducts.setDefaultCapable(false);
        btnProducts.setFocusPainted(false);
        btnProducts.setMaximumSize(new java.awt.Dimension(78, 36));
        btnProducts.setMinimumSize(new java.awt.Dimension(78, 36));
        btnProducts.setPreferredSize(new java.awt.Dimension(70, 22));
        btnProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductsMouseClicked(evt);
            }
        });
        btnProducts.addActionListener(this::btnProductsActionPerformed);

        btnClients.setBackground(new java.awt.Color(33, 150, 243));
        btnClients.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnClients.setForeground(new java.awt.Color(255, 255, 255));
        btnClients.setText("Clientes");
        btnClients.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClients.setBorderPainted(false);
        btnClients.setContentAreaFilled(false);
        btnClients.setDefaultCapable(false);
        btnClients.setFocusPainted(false);
        btnClients.setMaximumSize(new java.awt.Dimension(78, 36));
        btnClients.setMinimumSize(new java.awt.Dimension(78, 36));
        btnClients.setPreferredSize(new java.awt.Dimension(78, 36));
        btnClients.addActionListener(this::btnClientsActionPerformed);

        btnInventario.setBackground(new java.awt.Color(33, 150, 243));
        btnInventario.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(255, 255, 255));
        btnInventario.setText("Inventario");
        btnInventario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInventario.setBorderPainted(false);
        btnInventario.setContentAreaFilled(false);
        btnInventario.setDefaultCapable(false);
        btnInventario.setFocusPainted(false);
        btnInventario.setPreferredSize(new java.awt.Dimension(70, 22));
        btnInventario.addActionListener(this::btnInventarioActionPerformed);

        btnStart.setBackground(new java.awt.Color(33, 150, 243));
        btnStart.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setText("Inicio");
        btnStart.setBorder(null);
        btnStart.setContentAreaFilled(false);
        btnStart.setDefaultCapable(false);
        btnStart.setFocusPainted(false);
        btnStart.setOpaque(true);
        btnStart.setPreferredSize(new java.awt.Dimension(70, 22));
        btnStart.addActionListener(this::btnStartActionPerformed);

        btnMesas.setBackground(new java.awt.Color(33, 150, 243));
        btnMesas.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnMesas.setForeground(new java.awt.Color(255, 255, 255));
        btnMesas.setText("Mesas");
        btnMesas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMesas.setBorderPainted(false);
        btnMesas.setContentAreaFilled(false);
        btnMesas.setDefaultCapable(false);
        btnMesas.setFocusPainted(false);
        btnMesas.setPreferredSize(new java.awt.Dimension(70, 22));
        btnMesas.addActionListener(this::btnMesasActionPerformed);

        btnReportes.setBackground(new java.awt.Color(33, 150, 243));
        btnReportes.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Reportes");
        btnReportes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReportes.setBorderPainted(false);
        btnReportes.setContentAreaFilled(false);
        btnReportes.setDefaultCapable(false);
        btnReportes.setFocusPainted(false);
        btnReportes.setPreferredSize(new java.awt.Dimension(70, 22));
        btnReportes.addActionListener(this::btnReportesActionPerformed);

        btnPedidos.setBackground(new java.awt.Color(33, 150, 243));
        btnPedidos.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnPedidos.setForeground(new java.awt.Color(255, 255, 255));
        btnPedidos.setText("Pedidos");
        btnPedidos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPedidos.setBorderPainted(false);
        btnPedidos.setContentAreaFilled(false);
        btnPedidos.setDefaultCapable(false);
        btnPedidos.setFocusPainted(false);
        btnPedidos.setPreferredSize(new java.awt.Dimension(70, 22));
        btnPedidos.addActionListener(this::btnPedidosActionPerformed);

        btnFacturacion.setBackground(new java.awt.Color(33, 150, 243));
        btnFacturacion.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnFacturacion.setForeground(new java.awt.Color(255, 255, 255));
        btnFacturacion.setText("Facturación");
        btnFacturacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFacturacion.setBorderPainted(false);
        btnFacturacion.setContentAreaFilled(false);
        btnFacturacion.setDefaultCapable(false);
        btnFacturacion.setFocusPainted(false);
        btnFacturacion.setPreferredSize(new java.awt.Dimension(70, 22));
        btnFacturacion.addActionListener(this::btnFacturacionActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnFacturacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMesas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPedidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInventario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClients, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(btnProducts, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClients, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        panelContenido.setBackground(new java.awt.Color(215, 227, 225));
        panelContenido.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getPanelContenido() {
        return panelContenido;
    }

    public JButton getBtnClients() {
        return btnClients;
    }

    public JButton getBtnFacturacion() {
        return btnFacturacion;
    }

    public JButton getBtnInventario() {
        return btnInventario;
    }

    public JButton getBtnMesas() {
        return btnMesas;
    }

    public JButton getBtnPedidos() {
        return btnPedidos;
    }

    public JButton getBtnProducts() {
        return btnProducts;
    }

    public JButton getBtnReportes() {
        return btnReportes;
    }

    public JButton getBtnStart() {
        return btnStart;
    }


    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed

    }//GEN-LAST:event_btnProductsActionPerformed

    private void btnClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientsActionPerformed

    }//GEN-LAST:event_btnClientsActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed


    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

    }//GEN-LAST:event_btnStartActionPerformed

    private void btnMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesasActionPerformed


    }//GEN-LAST:event_btnMesasActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed

    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed

    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionActionPerformed


    }//GEN-LAST:event_btnFacturacionActionPerformed

    private void btnProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClients;
    private javax.swing.JButton btnFacturacion;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnMesas;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnProducts;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel panelContenido;
    // End of variables declaration//GEN-END:variables
}
