/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Product;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import javax.swing.*;

/**
 *
 * @author Personal
 */
public class ProductCard extends javax.swing.JPanel {

    /**
     * Creates new form ProductCard
     */
    private JPanel top;
    private JLabel lblPrecio;

    public ProductCard() {
        initComponents();
    }

    public ProductCard(Product p, Runnable onClick) {
        setPreferredSize(new Dimension(120, 150));
        setBackground(Color.WHITE);
        setBorder(BorderFactory.createLineBorder(new Color(210, 210, 210)));
        setLayout(new BorderLayout());
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        top = new JPanel(new BorderLayout());
        top.setBackground(new Color(210, 210, 210));
        top.setPreferredSize(new Dimension(170, 90));
        top.setOpaque(true);

        JLabel lblImg = new JLabel("", JLabel.CENTER);
        lblImg.setIcon(cargarIcono("/img/" + p.getImage(), 70, 70));
        top.add(lblImg, BorderLayout.CENTER);

        JPanel bottom = new JPanel();
        bottom.setBackground(Color.WHITE);
        bottom.setLayout(new BoxLayout(bottom, BoxLayout.Y_AXIS));
        bottom.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        JLabel lblNombre = new JLabel(p.getNameProduct());
        lblNombre.setFont(new Font("Segoe UI", Font.BOLD, 12));
        lblNombre.setAlignmentX(Component.CENTER_ALIGNMENT);

        lblPrecio = new JLabel("₡" + (int) p.getPrice());
        lblPrecio.setFont(new Font("Segoe UI", Font.BOLD, 12));
        lblPrecio.setAlignmentX(Component.CENTER_ALIGNMENT);

        bottom.add(lblNombre);
        bottom.add(Box.createVerticalStrut(6));
        bottom.add(lblPrecio);

        add(top, BorderLayout.NORTH);
        add(bottom, BorderLayout.CENTER);

        // pintar según stock
        setStockDisponible(p.getCant() > 0);

        // click
        MouseAdapter click = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                onClick.run();
            }
        };
        addMouseListener(click);
        top.addMouseListener(click);
        bottom.addMouseListener(click);
        lblImg.addMouseListener(click);
        lblNombre.addMouseListener(click);
        lblPrecio.addMouseListener(click);
    }

    private ImageIcon cargarIcono(String path, int w, int h) {
        URL url = getClass().getResource(path);
        if (url == null) {
            return null;
        }
        Image img = new ImageIcon(url).getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
        return new ImageIcon(img);
    }

    public void setStockDisponible(boolean disponible) {
        if (disponible) {
            top.setBackground(new Color(80, 200, 120));
            lblPrecio.setForeground(new Color(0, 140, 0));
        } else {
            top.setBackground(new Color(220, 60, 60));
            lblPrecio.setForeground(new Color(220, 60, 60));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
