/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author dh057
 *
 * Clase Vista encargada del módulo Reportes del Negocio.
 *
 * Se encarga de:
 * - Mostrar en una tabla los reportes generados a partir de los pedidos.
 * - Permitir búsquedas o filtrado de información mediante campos de texto.
 * - Proporcionar botones para ejecutar acciones como consultar, filtrar o actualizar datos.
 *
 * Esta clase forma parte de la capa Vista dentro del patrón MVC.
 * No contiene lógica de negocio ni acceso a datos; únicamente
 * gestiona los componentes gráficos del módulo.
 */
public class ReportesNegocio extends javax.swing.JPanel {

    /**
     * Constructor:
     * - Inicializa todos los componentes gráficos del panel.
     * - Configura la estructura visual generada por el Form Editor.
     *
     * No recibe parámetros y no retorna valores.
     */
    public ReportesNegocio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnFiltrarPorMesas = new javax.swing.JButton();
        jbtnFiltrarGeneral = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCargarReportes = new javax.swing.JTable();
        jLabelMenjaFiltrarPor = new javax.swing.JLabel();
        txtIdBuscador = new javax.swing.JTextField();

        setBackground(new java.awt.Color(236, 240, 241));

        jbtnFiltrarPorMesas.setBackground(new java.awt.Color(204, 204, 204));
        jbtnFiltrarPorMesas.setForeground(new java.awt.Color(255, 255, 255));
        jbtnFiltrarPorMesas.setText("Mesas");

        jbtnFiltrarGeneral.setBackground(new java.awt.Color(33, 150, 243));
        jbtnFiltrarGeneral.setForeground(new java.awt.Color(255, 255, 255));
        jbtnFiltrarGeneral.setText("General");
        jbtnFiltrarGeneral.setPreferredSize(new java.awt.Dimension(91, 23));

        jTableCargarReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCargarReportes);

        jLabelMenjaFiltrarPor.setBackground(new java.awt.Color(0, 0, 0));
        jLabelMenjaFiltrarPor.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabelMenjaFiltrarPor.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMenjaFiltrarPor.setText("Filtrar por:");

        txtIdBuscador.setBackground(new java.awt.Color(255, 255, 255));
        txtIdBuscador.setForeground(new java.awt.Color(0, 0, 0));
        txtIdBuscador.addActionListener(this::txtIdBuscadorActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMenjaFiltrarPor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jbtnFiltrarPorMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnFiltrarGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnFiltrarGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnFiltrarPorMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMenjaFiltrarPor)
                    .addComponent(txtIdBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdBuscadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelMenjaFiltrarPor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCargarReportes;
    private javax.swing.JButton jbtnFiltrarGeneral;
    private javax.swing.JButton jbtnFiltrarPorMesas;
    private javax.swing.JTextField txtIdBuscador;
    // End of variables declaration//GEN-END:variables
    /*
     *metodos getter y setter para obtener acceso.
     */
    public JLabel getjLabelMenjaFiltrarPor() {
        return jLabelMenjaFiltrarPor;
    }

    public void setjLabelMenjaFiltrarPor(JLabel jLabelMenjaFiltrarPor) {
        this.jLabelMenjaFiltrarPor = jLabelMenjaFiltrarPor;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getjTableCargarReportes() {
        return jTableCargarReportes;
    }

    public void setjTableCargarReportes(JTable jTableCargarReportes) {
        this.jTableCargarReportes = jTableCargarReportes;
    }

    public JButton getJbtnFiltrarGeneral() {
        return jbtnFiltrarGeneral;
    }

    public void setJbtnFiltrarGeneral(JButton jbtnFiltrarGeneral) {
        this.jbtnFiltrarGeneral = jbtnFiltrarGeneral;
    }

    public JButton getJbtnFiltrarPorMesas() {
        return jbtnFiltrarPorMesas;
    }

    public void setJbtnFiltrarPorMesas(JButton jbtnFiltrarPorMesas) {
        this.jbtnFiltrarPorMesas = jbtnFiltrarPorMesas;
    }

    public JTextField getTxtIdBuscador() {
        return txtIdBuscador;
    }

    public void setTxtIdBuscador(JTextField txtIdBuscador) {
        this.txtIdBuscador = txtIdBuscador;
    }
    
}
